// <auto-generated />
using System;
using GlobalHatim.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalHatim.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604091135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hatim_status", "hatim_status", new[] { "draft", "active", "completed", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "join_request_status", "join_request_status", new[] { "pending", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "juz_allocation_status", "juz_allocation_status", new[] { "available", "assigned", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participant_role", "participant_role", new[] { "manager", "reader" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "plan_type", "plan_type", new[] { "every2days1juz", "weekly_no_accel", "long_term_hybrid" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalHatim.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmailOrPhone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_or_phone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<bool>("IsReplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_replied");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.Hatim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_user_id");

                    b.Property<int>("CurrentCycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_cycle");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalCycles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_cycles");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("idx_hatims_creator");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("invite_code IS NOT NULL");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("idx_hatims_is_public");

                    b.HasIndex("PlanType")
                        .HasDatabaseName("idx_hatims_plan_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_hatims_status");

                    b.ToTable("hatims", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_tr");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("hatim_categories", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("HatimId")
                        .HasColumnType("uuid")
                        .HasColumnName("hatim_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("HatimId", "Status")
                        .HasDatabaseName("idx_join_requests_hatim_status");

                    b.HasIndex("HatimId", "UserId")
                        .IsUnique();

                    b.ToTable("hatim_join_requests", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("HatimId")
                        .HasColumnType("uuid")
                        .HasColumnName("hatim_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Reader")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_participants_user");

                    b.HasIndex("HatimId", "UserId")
                        .IsUnique();

                    b.ToTable("hatim_participants", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.JuzAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CycleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cycle_number");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<string>("GuestFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("guest_first_name");

                    b.Property<string>("GuestLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("guest_last_name");

                    b.Property<string>("GuestToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("guest_token");

                    b.Property<Guid>("HatimId")
                        .HasColumnType("uuid")
                        .HasColumnName("hatim_id");

                    b.Property<short>("JuzNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("idx_juz_alloc_user");

                    b.HasIndex("GuestToken")
                        .IsUnique()
                        .HasDatabaseName("idx_juz_alloc_guest_token")
                        .HasFilter("guest_token IS NOT NULL");

                    b.HasIndex("JuzNumber");

                    b.HasIndex("HatimId", "Status")
                        .HasDatabaseName("idx_juz_alloc_hatim_status");

                    b.HasIndex("HatimId", "CycleNumber", "JuzNumber")
                        .IsUnique();

                    b.ToTable("juz_allocations", null, t =>
                        {
                            t.HasCheckConstraint("chk_single_assignee", "(assigned_user_id IS NOT NULL AND guest_first_name IS NULL AND guest_token IS NULL)\n              OR (assigned_user_id IS NULL AND guest_first_name IS NOT NULL AND guest_token IS NOT NULL)\n              OR (assigned_user_id IS NULL AND guest_first_name IS NULL AND guest_token IS NULL)");
                        });
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.JuzLookup", b =>
                {
                    b.Property<short>("JuzNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("JuzNumber"));

                    b.Property<string>("AssociatedSurahNamesAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("associated_surah_names_ar");

                    b.Property<string>("AssociatedSurahNamesTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("associated_surah_names_tr");

                    b.Property<short>("EndPage")
                        .HasColumnType("smallint")
                        .HasColumnName("end_page");

                    b.Property<short>("StartPage")
                        .HasColumnType("smallint")
                        .HasColumnName("start_page");

                    b.HasKey("JuzNumber");

                    b.ToTable("juz_lookup", null, t =>
                        {
                            t.HasCheckConstraint("chk_juz_number_range", "juz_number BETWEEN 1 AND 30");
                        });
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.ReadingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CycleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cycle_number");

                    b.Property<Guid>("HatimId")
                        .HasColumnType("uuid")
                        .HasColumnName("hatim_id");

                    b.Property<short>("JuzNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId")
                        .IsUnique();

                    b.HasIndex("ConfirmedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_reading_log_confirmed");

                    b.HasIndex("HatimId")
                        .HasDatabaseName("idx_reading_log_hatim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reading_log_user");

                    b.ToTable("reading_log", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.RotationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("ActualRotationDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_rotation_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_number");

                    b.Property<Guid>("HatimId")
                        .HasColumnType("uuid")
                        .HasColumnName("hatim_id");

                    b.Property<bool>("IsRamadanPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ramadan_period");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("HatimId", "CycleNumber")
                        .IsUnique();

                    b.ToTable("rotation_schedule", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BadgeIcon")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("badge_icon");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinJuzRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_juz_read");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_tr");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("user_levels", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("tr")
                        .HasColumnName("language");

                    b.Property<bool>("NotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notification_enabled");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("TotalHatimsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_hatims_completed");

                    b.Property<int>("TotalHatimsCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_hatims_created");

                    b.Property<int>("TotalHatimsJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_hatims_joined");

                    b.Property<int>("TotalJuzRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_juz_read");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.Hatim", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.HatimCategory", "Category")
                        .WithMany("Hatims")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlobalHatim.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimJoinRequest", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.Hatim", "Hatim")
                        .WithMany("JoinRequests")
                        .HasForeignKey("HatimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalHatim.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hatim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimParticipant", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.Hatim", "Hatim")
                        .WithMany("Participants")
                        .HasForeignKey("HatimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalHatim.Domain.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hatim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.JuzAllocation", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.User", "AssignedUser")
                        .WithMany("Allocations")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlobalHatim.Domain.Entities.Hatim", "Hatim")
                        .WithMany("JuzAllocations")
                        .HasForeignKey("HatimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalHatim.Domain.Entities.JuzLookup", "JuzInfo")
                        .WithMany("Allocations")
                        .HasForeignKey("JuzNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Hatim");

                    b.Navigation("JuzInfo");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.ReadingLog", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.JuzAllocation", "Allocation")
                        .WithOne("ReadingLog")
                        .HasForeignKey("GlobalHatim.Domain.Entities.ReadingLog", "AllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlobalHatim.Domain.Entities.Hatim", "Hatim")
                        .WithMany()
                        .HasForeignKey("HatimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalHatim.Domain.Entities.User", "User")
                        .WithMany("ReadingLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Allocation");

                    b.Navigation("Hatim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.RotationSchedule", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.Hatim", "Hatim")
                        .WithMany("RotationSchedules")
                        .HasForeignKey("HatimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hatim");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.User", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.UserLevel", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Level");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("GlobalHatim.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserStats", b =>
                {
                    b.HasOne("GlobalHatim.Domain.Entities.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("GlobalHatim.Domain.Entities.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.Hatim", b =>
                {
                    b.Navigation("JoinRequests");

                    b.Navigation("JuzAllocations");

                    b.Navigation("Participants");

                    b.Navigation("RotationSchedules");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.HatimCategory", b =>
                {
                    b.Navigation("Hatims");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.JuzAllocation", b =>
                {
                    b.Navigation("ReadingLog");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.JuzLookup", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.User", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Participations");

                    b.Navigation("ReadingLogs");

                    b.Navigation("Settings");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("GlobalHatim.Domain.Entities.UserLevel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
